#!/usr/bin/env bash
# configure a new nginx web server
# install the Nginx
sudo apt-get -y update
sudo apt-get -y install nginx
# enable pass of traffic in the port 80
sudo ufw allow 'Nginx HTTP'
#copy the content in the index.html file tee cuz > or >> dont work
echo "Hello World" |sudo tee /var/www/html/index.html
# start Nginx service
sudo service nginx start
