#!/usr/bin/env bash
# fixing the start of nginx,the fail was because there are two files differents
# the /etc/nginx/sites-availables/default and /etc/nginx/sites-enables/default
# we have to change the enables to listen port 80 and erase the ~ file
cd /etc/nginx/sites-enabled/
sudo sed -i "s/listen 8080/ listen 80/" default
sudo sed -i "s/8080/80/" default
# as we see the default of enables dir was set at 8080 not 80
# remove the posible others files that dont have the new configuration
rm ./*~
cd ~
# refresh changes
sudo service nginx reload
sudo service nginx start
