#!/usr/bin/env bash
# script for fix problem stop process instead of kill it
sudo sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo kill -9 "$(cat /run/nginx.pid)"
