#!/usr/bin/env bash
# if we cange the owner we can run the nginx as if we set the user
pkill -o apache2
chmod 744 /etc/nginx/nginx.conf
chown nginx:nginx -R /etc/nginx/
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
su nginx -c 'service nginx restart'
